### ISSUE TITLE
Undefined control sequence

### ISSUE THREAD

**Issue by Sk1nk** [Sophanatprime/updatemarks#1]
First of all, thanks! 

I downloaded your file and dropped it into the folder and ran it with the command suggested by you over at tcolorbox. But I get the error

"Undefined control sequence. (...nDocument{\updatemarks@tcolorbox@patch}}} ...)"

**Comment by Sophanatprime** [comment]
Now it should work with old TeXLive (TeXLive 2018 - TeXLive 2023, TeXLive 2018 - TeXLive 2022 in overleaf).

**Comment by Sk1nk** [comment]
Unrelated, but is there a way to get your package via TeXLive? At the moment I get: 
```
sudo tlmgr install updatemarks
Password:
tlmgr: package repository https://ftp.fau.de/ctan/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr install: package updatemarks not present in repository.
tlmgr: action install returned an error; continuing.
tlmgr: An error has occurred. See above messages. Exiting.
```

BTW: Update works now, thanks for the quick response AND for the help with my problem

**Comment by Sophanatprime** [comment]
After I figure out how to make it work with `multicol` package (and write documentation, of course), I will upload to CTAN. Should be soon.

**Comment by Sophanatprime** [comment]
You can install this package by using tlmgr now.
